services:
    api:
        build:
            context: ./api
        image: ghcr.io/isaacakajupiter/isaacs-simple-media/api:latest
        container_name: ism-api
        restart: unless-stopped
        ports:
            - '3333:3333'
        volumes:
            - ism_db_data:/data
            - ism_upload:/upload
            - ism_import:/import
        environment:
            - PORT=3333
            - DATABASE_PATH=/data/ism.db
            - UPLOAD_DIRECTORY=/upload
            - IMPORT_DIRECTORY=/import
            - REDIS_HOST=valkey
            - REDIS_PORT=6379
            - REDIS_KEY_PREFIX=ism
        networks:
            - ism_internal
        depends_on:
            - valkey

    web:
        build:
            context: ./web
        image: ghcr.io/isaacakajupiter/isaacs-simple-media/web:latest
        container_name: ism-web
        restart: unless-stopped
        ports:
            - '3334:3334'
        environment:
            - PORT=3334
        networks:
            - ism_internal
        depends_on:
            - api

    valkey:
        image: valkey/valkey
        container_name: ism-valkey
        restart: unless-stopped
        volumes:
            - ism_redis_data:/data
        networks:
            - ism_internal

volumes:
    ism_redis_data:
    ism_db_data:
    ism_upload:
    ism_import:

networks:
    ism_internal:
        driver: bridge
