name: Publish Docker Images on Release

on:
    release:
        types: [published]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: downcase REPO
              run: |
                  echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

            - name: use REPO
              run: |
                  echo "The value of REPO is: ${REPO}"

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push API image
              uses: docker/build-push-action@v5
              with:
                  context: ./api
                  push: true
                  tags: |
                      ghcr.io/${REPO}/api:latest
                      ghcr.io/${REPO}/api:${{ github.ref_name }}
            - name: Build and push Web image
              uses: docker/build-push-action@v5
              with:
                  context: ./web
                  push: true
                  tags: |
                      ghcr.io/${REPO}/web:latest
                      ghcr.io/${REPO}/web:${{ github.ref_name }}
